#!/usr/bin/env node
// searchCheck.js (Oct 2026): the nightly enforcement of docs/search-rules.md on the LIVE public pages.
// Fetches a small set of public URLs (home, /buy, /sell, /mcp, and 3 real VIN pages pulled from
// vin_summary so the check maintains itself) and FAILS (exit 1) if any page has a missing or duplicate
// <title>, a missing <h1>, no lead sentence, no <link rel=canonical>, or is noindex yet present in a
// sitemap. /sell is the one named exception (rule 1): it carries a quiet "Updated [date]" line instead
// of a dated lead sentence and that satisfies the check there - every other page stays strict. Runs in
// the nightly workflow AFTER the spec-cache step and logs its result to app_usage_events (event_type
// "search_check"). Read-only, zero OldCarsData.
//
//   node scripts/searchCheck.js [--base=https://goasksam.com] [--report]
import { supabaseEnv, supabaseSelect } from "../lib/_supabase.js";

const arg = (k, d) => { const a = process.argv.find(x => x.startsWith(`--${k}=`)); return a ? a.split("=")[1] : d; };
const REPORT_ONLY = process.argv.includes("--report");
const BASE = (arg("base", process.env.SEARCH_BASE || "https://goasksam.com")).replace(/\/$/, "");

const strip = s => String(s || "").replace(/<[^>]+>/g, " ").replace(/&[a-z]+;/gi, " ").replace(/\s+/g, " ").trim();
function parsePage(html) {
  const h = String(html || "");
  const title = (/(<title[^>]*>)([\s\S]*?)<\/title>/i.exec(h) || [])[2];
  const h1 = (/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(h) || [])[1];
  const canon = /<link[^>]+rel=["']canonical["'][^>]*>/i.test(h);
  const noindex = /<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i.test(h);
  // Lead sentence: the explicit [data-lead-sentence] marker (the convention), else the first substantial <p>.
  let lead = (/<[^>]+data-lead-sentence[^>]*>([\s\S]*?)<\//i.exec(h) || [])[1];
  if (!strip(lead)) { for (const m of h.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)) { if (strip(m[1]).length >= 30) { lead = m[1]; break; } } }
  // /sell-only exception (Oct 2026, Sam): /sell dropped its dated lead sentence for a small quiet
  // "Updated [date]" line (lib/asOf.js lastUpdatedDate - the real last-ingest date, no count). Detected
  // by TEXT PATTERN (not a class name) so it stays robust to markup changes: "Updated October 8, 2026"
  // anywhere in the body. Every other page keeps the strict lead-sentence requirement unchanged.
  const updatedLine = /\bUpdated\s+[A-Z][a-z]+\s+\d{1,2},\s+\d{4}\b/.test(strip(h));
  return { title: strip(title), h1: strip(h1), canonical: canon, noindex, lead: strip(lead), updatedLine };
}

// The Vercel Security Checkpoint 429s automated fetches; the project bypass secret (same one warm.js
// uses) clears it. Browsers are unaffected. Absent -> the nightly may see 429s, which is a loud fail.
const BYPASS = process.env.VERCEL_AUTOMATION_BYPASS_SECRET || "";
async function getText(url) {
  const headers = { "user-agent": "GoAskSam-searchCheck", ...(BYPASS ? { "x-vercel-protection-bypass": BYPASS } : {}) };
  try { const r = await fetch(url, { redirect: "follow", headers, signal: AbortSignal.timeout(25000) }); return { ok: r.ok, status: r.status, finalUrl: r.url, body: await r.text() }; }
  catch (e) { return { ok: false, status: 0, finalUrl: url, body: "", err: String(e && e.message || e) }; }
}

// Collect listed page URLs from the STATIC sitemaps only (pages/specs/hubs). We deliberately do NOT
// crawl the dynamic VIN sitemap here: it is a 300s DB-scan function we don't want to hammer nightly,
// and it is generated by the SAME index rule as the VIN page itself, so by construction it can never
// list a noindex VIN. The noindex-in-sitemap check below therefore covers the static pages; VIN
// noindex/sitemap coherence is guaranteed at generation time in api/history.js.
async function sitemapUrls() {
  const set = new Set();
  for (const sm of ["sitemap-pages.xml", "sitemap-specs.xml", "sitemap-hubs.xml"]) {
    const r = await getText(`${BASE}/${sm}`);
    if (r.ok) for (const m of r.body.matchAll(/<loc>([^<]+)<\/loc>/gi)) set.add(m[1].trim().replace(/\/$/, ""));
  }
  return set;
}

async function main() {
  const env = supabaseEnv();
  // 3 real VIN pages, newest multi-appearance cars (self-maintaining). Fall back to a known VIN.
  let vins = [];
  if (env) {
    const rows = await supabaseSelect(env, `vin_summary?select=vin_norm&make=not.is.null&order=last_seen.desc&limit=3`).catch(() => null);
    vins = (rows || []).map(r => r.vin_norm).filter(Boolean);
  }
  if (!vins.length) vins = ["WBSDE93483CF93837"];
  const urls = [`${BASE}/`, `${BASE}/buy`, `${BASE}/sell`, `${BASE}/mcp`, `${BASE}/market-check`, `${BASE}/cars/porsche/911`, `${BASE}/cars/porsche/911/993/carrera/coupe-manual`, ...vins.map(v => `${BASE}/vin/${v}`)];

  const inSitemap = await sitemapUrls();
  const results = [];
  const seenFinal = new Set();
  for (const u of urls) {
    const r = await getText(u);
    // A redirect to a page already checked (e.g. / -> /sell) is the SAME page, not a duplicate.
    const fin = (r.finalUrl || u).replace(/\/$/, "");
    if (seenFinal.has(fin)) continue;
    seenFinal.add(fin);
    const p = r.ok ? parsePage(r.body) : {};
    results.push({ url: u, finalUrl: r.finalUrl, status: r.status, ok: r.ok, ...p });
  }

  // Duplicate-title detection across the set.
  const byTitle = new Map();
  for (const r of results) if (r.title) byTitle.set(r.title, (byTitle.get(r.title) || 0) + 1);

  const failures = [];
  for (const r of results) {
    const where = r.url.replace(BASE, "");
    if (!r.ok) { failures.push(`${where}: HTTP ${r.status}${r.err ? " " + r.err : ""}`); continue; }
    if (!r.title) failures.push(`${where}: missing <title>`);
    else if (byTitle.get(r.title) > 1) failures.push(`${where}: duplicate <title> ("${r.title}")`);
    if (!r.h1) failures.push(`${where}: missing <h1>`);
    // /sell-only exception: a quiet "Updated [date]" line stands in for the dated lead sentence there.
    // Every other page is unaffected - still requires [data-lead-sentence] or a substantial first <p>.
    const isSell = (r.finalUrl || r.url).replace(/\/$/, "").endsWith("/sell");
    if (!r.lead && !(isSell && r.updatedLine)) failures.push(`${where}: no lead sentence (add [data-lead-sentence] or a substantial first <p>)${isSell ? ' (or an "Updated [date]" line for /sell)' : ""}`);
    if (!r.canonical) failures.push(`${where}: no <link rel=canonical>`);
    if (r.noindex && inSitemap.has(r.finalUrl.replace(/\/$/, ""))) failures.push(`${where}: noindex page is present in a sitemap`);
  }

  const pass = failures.length === 0;
  console.log(`searchCheck: ${results.length} pages, ${pass ? "PASS" : failures.length + " FAILURE(S)"}`);
  for (const r of results) console.log(`  ${r.ok ? "ok " : "ERR"} ${r.url.replace(BASE, "")}  title=${r.title ? "y" : "n"} h1=${r.h1 ? "y" : "n"} lead=${r.lead ? "y" : "n"}${r.updatedLine ? " updated=y" : ""} canon=${r.canonical ? "y" : "n"}${r.noindex ? " noindex" : ""}`);
  if (!pass) { console.log("FAILURES:"); for (const f of failures) console.log(`  - ${f}`); }

  if (env) {
    try {
      const { recordUsageEvent } = await import("../api/_usage.js");
      await recordUsageEvent({ event_type: "search_check", route: "scripts/searchCheck.js", status: pass ? "ok" : "fail", oldcarsdata_metered_requests: 0, metadata: { base: BASE, checked: results.length, failures } }, env.supabaseUrl, env.supabaseKey);
    } catch { /* best-effort */ }
  }
  if (!pass && !REPORT_ONLY) { console.error("::error::searchCheck failed"); process.exit(1); }
}

main().catch(e => { console.error("searchCheck crashed:", e); process.exit(1); });
